version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      # Override MONGO_URI from .env so container talks to the mongo service
      MONGO_URI: mongodb://mongo:27017?directConnection=true
      # Point to AI model server container
      AI_MODEL_API_URL: http://ai-model:5000/check-comment
    networks:
      - app-network

  frontend:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  ai-model:
    build:
      context: ./ai_model_server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - app-network

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local